// hello-world/app/solidjs/src/App.tsx
import type { Component } from 'solid-js';

import Logo from './assets/logo.png';
import styles from './App.module.css';
import {Header, HelloWorld, PolywrapProvider } from "./components";

const App: Component = () => {
  return (
    <PolywrapProvider>
      <Header />
      <div class={styles.main}>
        <img src={Logo} class={styles.main__logo} />
        <HelloWorld />
      </div>
    </PolywrapProvider>
  );
};

export default App;

// old/fetch-metadata/src/App.tsx
import React from 'react';
import { PolywrapProvider } from '@polywrap/react';
import { Header } from './components/Header/Header';
import './App.css';
import {ThemeProvider} from "@mui/material";
import {darkTheme} from "./theme";
import {Main} from "./pages/Main";

export const App: React.FC = () => {
  return (
    <PolywrapProvider>
      <ThemeProvider theme={darkTheme}>
        <div className="root">
          <Header />
          <Main />
        </div>
      </ThemeProvider>
    </PolywrapProvider>
  );
};
