// hello-world/app/solidjs/src/App.tsx
import type { Component } from 'solid-js';

import Logo from './assets/logo.png';
import styles from './App.module.css';
import {Header, HelloWorld, PolywrapProvider } from "./components";

const App: Component = () => {
  return (
    <PolywrapProvider>
      <Header />
      <div class={styles.main}>
        <img src={Logo} class={styles.main__logo} />
        <HelloWorld />
      </div>
    </PolywrapProvider>
  );
};

export default App;

// hello-world/app/react-js/src/App.tsx
import React from 'react';
import { PolywrapProvider } from '@polywrap/react';
import { HelloWorld } from './HelloWorld';
import { Header } from './Header';
import Logo from './logo.png';
import './App.css';
import {ClientConfigBuilder} from "@polywrap/client-js";

export const App: React.FC = () => {

  const config = new ClientConfigBuilder().addDefaults().config

  return (
    <PolywrapProvider
      wrappers={config.wrappers}
      packages={config.packages}
      envs={config.envs}
      interfaces={config.interfaces}
      redirects={config.redirects}
      resolvers={config.resolvers}
    >
      <Header />
      <div className='main'>
        <img src={Logo} className='main__logo' />
        <HelloWorld />
      </div>
    </PolywrapProvider>
  );
};
